"""
Pydantic schemas for datasets, profiling, KPIs, trends, anomalies, agent analysis, and reports.
"""

from backend.app.schemas.common import HealthResponse, StandardErrorResponse
from backend.app.schemas.dataset import (
    ColumnDescription,
    QualitySummary,
    DatasetMetadata,
    DatasetUploadResponse,
    DatasetListResponse,
    ColumnType,
    ColumnProfile,
    DataQualityIssue,
    DataQualitySummary,
    DatasetProfile,
)
from backend.app.schemas.analysis import (
    AnalysisQueryRequest,
    AgentPlanOutput,
    AgentQueryResponse,
    AnalysisHistoryItem,
    AnalysisHistoryResponse,
    ChartSpec,
)
from backend.app.schemas.analytics import (
    KPIMetricType,
    KPIMetricConfig,
    KPIMetricResult,
    KPIEngineResult,
    TrendPoint,
    TrendDirection,
    TrendResult,
    AnomalyPoint,
    AnomalyResult,
    GroupedMetricResult,
    ChartType,
    AnalysisType,
    AnalysisResult,
    ChartSpec as AnalyticsChartSpec,
)
from backend.app.schemas.report import ReportGenerateRequest, ReportResponse, ReportSection

__all__ = [
    "HealthResponse",
    "StandardErrorResponse",
    "ColumnDescription",
    "QualitySummary",
    "DatasetMetadata",
    "DatasetUploadResponse",
    "DatasetListResponse",
    "ColumnType",
    "ColumnProfile",
    "DataQualityIssue",
    "DataQualitySummary",
    "DatasetProfile",
    "AnalysisQueryRequest",
    "AgentPlanOutput",
    "AgentQueryResponse",
    "AnalysisHistoryItem",
    "AnalysisHistoryResponse",
    "ChartSpec",
    "AnalyticsChartSpec",
    "KPIMetricType",
    "KPIMetricConfig",
    "KPIMetricResult",
    "KPIEngineResult",
    "TrendPoint",
    "TrendDirection",
    "TrendResult",
    "AnomalyPoint",
    "AnomalyResult",
    "GroupedMetricResult",
    "ChartType",
    "AnalysisType",
    "AnalysisResult",
    "ReportGenerateRequest",
    "ReportResponse",
    "ReportSection",
]
